# Contenido de las paginas de plataforma de tienda (una por plataforma).
# El armado lo hace armar-plataformas.py sobre el molde de servicio-tiendas-online.html.
# Regla: solo afirmaciones que ya estan probadas en el sitio (FAQ, casos, plazos).
# Precios: el sitio dice "A cotizar"; no se escriben cifras.

PLATAFORMAS = [
{
"archivo": "servicio-tiendanube.html",
"nombre": "Tiendanube",
"logo": ("tiendanube.png", "Logo de Tiendanube", True),
"title": "Desarrollo de Tiendas en Tiendanube a Medida - Studio Complex",
"desc": "Armamos tu tienda en Tiendanube a medida: diseño propio, Mercado Pago, envíos, carga de productos y SEO. Plazo y precio cerrado por escrito.",
"service_name": "Tiendas en Tiendanube",
"service_type": "Desarrollo y migración de tiendas online en Tiendanube",
"eyebrow": "Tiendanube",
"h1": 'Tu tienda en <span class="sc-sv-grad">Tiendanube</span>, armada a medida.',
"lead": "Diseñamos, armamos y lanzamos tu tienda en Tiendanube: catálogo cargado, pagos y envíos resueltos, SEO desde el primer día y la posibilidad de automatizar lo que hoy hacés a mano. También te mudamos desde otra plataforma sin perder el posicionamiento.",
"datos": [("3 a 6 sem.", "para una tienda completa"), ("+800", "productos en un caso"), ("69", "categorías en ese caso")],
"cinta": ["Diseño a medida", "Mercado Pago", "Envíos configurados", "Carga de productos", "SEO de la tienda", "Migración sin perder Google", "Carrito abandonado", "Automatizaciones", "Píxel y analítica"],
"formatos_eyebrow": "Cómo trabajamos",
"formatos_h2": "Tres formas de empezar con Tiendanube.",
"formatos_lead": "Tiendanube es simple de manejar y trae pagos y envíos de la región ya integrados. Según dónde estés parado, arrancamos de una de estas tres maneras.",
"formatos": [
  ("De 3 a 6 semanas", "Tienda nueva", "Tu tienda en Tiendanube desde cero, con diseño propio, los productos cargados y los pagos y envíos funcionando.",
   ["Diseño a medida de tu marca", "Carga del catálogo", "Pagos, envíos y analítica"], "vendés por Instagram o WhatsApp y querés que la venta se haga sola.", False),
  ("Según el alcance", "Rediseño y funciones a medida", "Para tiendas con mucho catálogo o un rubro con reglas propias, donde la plantilla se queda corta.",
   ["Menú y navegación programados", "Funciones propias del rubro", "Capacitación al entregar"], "tu tienda ya vende y ahora tiene que vender más.", True),
  ("Según la cantidad de productos", "Migración a Tiendanube", "Te mudamos desde WooCommerce, Shopify u otra plataforma, con productos, fotos y categorías, y cuidamos lo que Google ya conocía.",
   ["Productos y variantes", "Redirecciones de las URL viejas", "Tienda nueva lista antes de apagar la vieja"], "tu plataforma actual te limita o te cobra de más.", False),
],
"incluye_eyebrow": "Qué incluye",
"incluye_h2": "Tu tienda en Tiendanube, lista para vender y para que te encuentren.",
"cajas": [
  ("tji-development", "Diseño que no parece plantilla", "Escribimos el diseño sobre el tema de tu tienda, no lo elegimos de una lista. Trabajamos primero en una copia, para no tocar la tienda que vende."),
  ("tji-budget", "Cobrás como tu cliente quiere pagar", "Mercado Pago, tarjetas en cuotas y transferencia, con sus recargos y promociones. Hacemos una compra real antes de lanzar."),
  ("tji-plane", "Envíos sin consultas", "El cliente ve cuánto sale y cuándo llega antes de pagar. Sumamos retiro en el local o envío en el día si lo hacés."),
  ("tji-window", "Catálogo cargado", "Subimos tus productos con fotos, variantes de talle y color, stock y precios. Si ya los tenés en una planilla, los importamos de una."),
  ("tji-search", "SEO de tu tienda", "Títulos y descripciones por producto y categoría, direcciones claras, datos estructurados y velocidad de carga. Para que te encuentren cuando buscan lo que vendés."),
  ("tji-chart", "Lista para anunciar", "Dejamos instalados el píxel de Meta, Google Analytics y el seguimiento de compras. Cuando prendas los anuncios, cada venta queda atribuida a la campaña."),
  ("tji-bell", "Carritos que vuelven", "El que dejó productos en el carrito recibe un recordatorio y vuelve a terminar la compra. También sumamos el botón de WhatsApp para el que prefiere preguntar antes."),
],
"auto_eyebrow": "Automatizaciones",
"auto_h2": "Lo que hoy hacés a mano en tu Tiendanube, que se haga solo.",
"auto_lead": "Conectamos tu tienda con las herramientas que ya usás. Se ve en un trabajo real: cuando el pago se acredita, el sistema da de alta al alumno y le abre el acceso, a cualquier hora y sin que nadie del equipo haga nada.",
"autos": [
  ("tiendanube.png", "Venta aprobada, alta automática", "Al acreditarse el pago, la tienda avisa y Make hace el resto: alta del cliente, accesos o aviso interno.", True),
  ("make.svg", "Sin tareas repetitivas", "Pedidos a una planilla o a tu CRM, avisos al equipo y mensajes de seguimiento. Lo armamos según tu caso.", False),
  ("whatsapp.svg", "Consultas bien repartidas", "Las consultas de WhatsApp se reparten entre asesores y cada una queda registrada con su origen.", False),
  ("googlesheets.svg", "Todo en un solo lugar", "Cada venta y cada consulta quedan ordenadas para saber qué funciona y dónde se pierden clientes.", False),
],
"auto_link": ("servicio-automatizacion-leads.html", "Ver el servicio de automatización"),
"proceso_lead": "Antes de empezar tenés el alcance, el plazo y el precio por escrito. Hablás siempre con quien está armando tu tienda.",
"pasos": [
  ("Diagnóstico", "Hablamos de qué vendés, cuántos productos tenés, cómo cobrás y cómo entregás. Con eso confirmamos si Tiendanube es la plataforma indicada o si te conviene otra.", "Sin cargo"),
  ("Propuesta", "Te pasamos qué incluye la tienda, cuánto tarda, cuánto sale y lo que cuesta mantener el plan de Tiendanube por mes.", ""),
  ("Diseño", "Ves la tienda diseñada con tus productos reales antes de armarla. La ajustamos con vos hasta que te cierre.", ""),
  ("Armado y carga", "Cargamos el catálogo, configuramos pagos y envíos, y hacemos compras de prueba reales hasta que todo sale bien.", ""),
  ("Lanzamiento y capacitación", "La publicamos en tu dominio y te enseñamos a cargar productos, ver pedidos y armar promociones. Después del lanzamiento hay una ronda de ajustes incluida.", "Seguimos disponibles para soporte"),
],
"casos": [
  ("caso-tienda-a-medida.html", "tienda-a-medida.jpg", "Tienda con menú programado a medida", "E-commerce a medida", "Una tienda con el menú programado a medida"),
  ("caso-plataforma-de-cursos.html", "plataforma-de-cursos.jpg", "Tiendanube, Make y aula virtual conectados", "Desarrollo a medida", "El alumno paga y entra al aula solo"),
  ("caso-retail-rubro-restringido.html", "retail-rubro-restringido.jpg", "Campañas de Google Ads para una tienda", "Gestión de campañas", "Google Ads en un rubro con restricciones"),
],
"casos_lead": "Cada caso cuenta el problema que había, cómo lo encaramos y qué cambió.",
"faq": [
  ("¿Cuánto cuesta una tienda en Tiendanube?", "Depende del diseño, de la cantidad de productos y de las funciones que necesites, por eso no hay un precio único. Después de la reunión te pasamos un precio cerrado por escrito. Aparte está el abono de Tiendanube, que pagás directo a la plataforma según el plan que elijas."),
  ("¿Cuánto tarda en estar lista?", "Una tienda completa lleva entre 3 y 6 semanas. Lo que más mueve el plazo es tener las fotos y los datos de los productos listos. Antes de arrancar tenés el cronograma con las fechas de cada etapa."),
  ("¿Se puede personalizar el diseño más allá de las plantillas?", "Sí. Escribimos el diseño sobre el tema de tu tienda. En un caso, una tienda con más de ochocientos productos y sesenta y nueve categorías necesitaba un menú con foto por categoría, que la plataforma no trae, y lo programamos. Trabajamos primero en una copia, para no tocar la tienda que vende."),
  ("Tengo una tienda en WooCommerce, Shopify u otra plataforma. ¿Pueden pasarla a Tiendanube?", "Sí. Pasamos productos, fotos y categorías, y redirigimos las direcciones viejas a las nuevas. La tienda vieja sigue andando hasta que la nueva está lista."),
  ("¿Qué pasa con mi posicionamiento en Google si migro?", "Redirigimos cada dirección vieja a la nueva con redirecciones 301, conservamos los títulos y textos que ya rinden y revisamos la indexación después de lanzar. Así Google no pierde lo que ya conocía de tu tienda."),
  ("¿Se conecta con Mercado Pago?", "Sí. Configuramos Mercado Pago junto con los otros medios de pago de la plataforma (tarjeta, transferencia y cuotas), con sus recargos y promociones, y hacemos una compra real antes de lanzar."),
  ("¿Pueden automatizar tareas de mi tienda?", "Sí, según tu caso. Por ejemplo, conectamos una tienda de cursos con su aula virtual: cuando el pago se acredita, el sistema da de alta al alumno y le abre el acceso solo, a cualquier hora. También armamos avisos de venta y el reparto de consultas de WhatsApp."),
  ("¿Me conviene Tiendanube, Shopify o WooCommerce?", "Depende de cuántos productos tenés, en qué países vendés y quién va a manejar la tienda. Tiendanube es simple y trae pagos y envíos de la región ya integrados. Shopify conviene si vendés en varios países o monedas, y WooCommerce si querés la tienda dentro de WordPress y sin abono de plataforma. En la reunión te recomendamos una y te explicamos por qué."),
  ("¿La tienda queda a mi nombre?", "Siempre. La cuenta de Tiendanube, el dominio y los medios de cobro son tuyos. Nosotros los configuramos y te dejamos todos los accesos."),
],
"rel": [
  ("servicio-tiendas-online.html", "tji-budget", "Tiendas online", "Tiendanube, Shopify o WooCommerce: cómo elegir la plataforma."),
  ("servicio-automatizacion-leads.html", "tji-bell", "Automatización de leads", "Que ninguna consulta se enfríe y cada una quede registrada."),
  ("servicio-seo-tecnico.html", "tji-search", "SEO Técnico", "Que te encuentren en Google cuando te buscan."),
  ("servicio-campanas-ads.html", "tji-rocket", "Campañas de Ads", "Google Ads y Meta Ads medidos de punta a punta."),
],
"cierre_h2": '¿Arrancamos con tu <span class="sc-sv-grad">tienda en Tiendanube</span>?',
"cierre_p": "Media hora de reunión y te decimos si Tiendanube es la plataforma indicada, cuánto tarda y cuánto sale.",
"wa_texto": "Hola, quiero consultar por una tienda en Tiendanube",
},
]
