# Contenido de las paginas de plataforma de tienda (una por plataforma).
# El armado lo hace armar-plataformas.py sobre el molde de servicio-tiendas-online.html.
# Regla: solo afirmaciones que ya estan probadas en el sitio (FAQ, casos, plazos).
# Precios: el sitio dice "A cotizar"; no se escriben cifras.

PLATAFORMAS = [
{
"archivo": "servicio-tiendanube.html",
"nombre": "Tiendanube",
"logo": ("tiendanube.png", "Logo de Tiendanube", True),
"title": "Desarrollo de Tiendas en Tiendanube a Medida - Studio Complex",
"desc": "Armamos tu tienda en Tiendanube a medida: diseño propio, Mercado Pago, envíos, carga de productos y SEO. Plazo y precio cerrado por escrito.",
"service_name": "Tiendas en Tiendanube",
"service_type": "Desarrollo y migración de tiendas online en Tiendanube",
"eyebrow": "Tiendanube",
"h1": 'Tu tienda en <span class="sc-sv-grad">Tiendanube</span>, armada a medida.',
"lead": "Diseñamos, armamos y lanzamos tu tienda en Tiendanube: catálogo cargado, pagos y envíos resueltos, SEO desde el primer día y la posibilidad de automatizar lo que hoy hacés a mano. También te mudamos desde otra plataforma sin perder el posicionamiento.",
"datos": [("3 a 6 sem.", "para una tienda completa"), ("+800", "productos en un caso"), ("69", "categorías en ese caso")],
"cinta": ["Diseño a medida", "Mercado Pago", "Envíos configurados", "Carga de productos", "SEO de la tienda", "Migración sin perder Google", "Carrito abandonado", "Automatizaciones", "Píxel y analítica"],
"formatos_eyebrow": "Cómo trabajamos",
"formatos_h2": "Tres formas de empezar con Tiendanube.",
"formatos_lead": "Tiendanube es simple de manejar y trae pagos y envíos de la región ya integrados. Según dónde estés parado, arrancamos de una de estas tres maneras.",
"formatos": [
  ("De 3 a 6 semanas", "Tienda nueva", "Tu tienda en Tiendanube desde cero, con diseño propio, los productos cargados y los pagos y envíos funcionando.",
   ["Diseño a medida de tu marca", "Carga del catálogo", "Pagos, envíos y analítica"], "vendés por Instagram o WhatsApp y querés que la venta se haga sola.", False),
  ("Según el alcance", "Rediseño y funciones a medida", "Para tiendas con mucho catálogo o un rubro con reglas propias, donde la plantilla se queda corta.",
   ["Menú y navegación programados", "Funciones propias del rubro", "Capacitación al entregar"], "tu tienda ya vende y ahora tiene que vender más.", True),
  ("Según la cantidad de productos", "Migración a Tiendanube", "Te mudamos desde WooCommerce, Shopify u otra plataforma, con productos, fotos y categorías, y cuidamos lo que Google ya conocía.",
   ["Productos y variantes", "Redirecciones de las URL viejas", "Tienda nueva lista antes de apagar la vieja"], "tu plataforma actual te limita o te cobra de más.", False),
],
"incluye_eyebrow": "Qué incluye",
"incluye_h2": "Tu tienda en Tiendanube, lista para vender y para que te encuentren.",
"cajas": [
  ("tji-development", "Diseño que no parece plantilla", "Escribimos el diseño sobre el tema de tu tienda, no lo elegimos de una lista. Trabajamos primero en una copia, para no tocar la tienda que vende."),
  ("tji-budget", "Cobrás como tu cliente quiere pagar", "Mercado Pago y los medios de pago que ya trae Tiendanube: tarjetas en cuotas y transferencia, con sus recargos y promociones. Probamos una compra real antes de salir."),
  ("tji-plane", "Envíos sin consultas", "El cliente ve cuánto sale y cuándo llega antes de pagar. Sumamos retiro en el local o envío en el día si lo hacés."),
  ("tji-window", "Catálogo cargado", "Subimos tus productos con fotos, variantes de talle y color, stock y precios. Si ya los tenés en una planilla, los importamos de una."),
  ("tji-search", "SEO de tu tienda", "Títulos y descripciones por producto y categoría, direcciones claras, datos estructurados y velocidad de carga. Para que te encuentren cuando buscan lo que vendés."),
  ("tji-chart", "Lista para anunciar", "Dejamos instalados el píxel de Meta, Google Analytics y el seguimiento de compras. Cuando prendas los anuncios, cada venta queda atribuida a la campaña."),
  ("tji-bell", "Carritos que vuelven", "El que dejó productos en el carrito recibe un recordatorio y vuelve a terminar la compra. También sumamos el botón de WhatsApp para el que prefiere preguntar antes."),
],
"auto_eyebrow": "Automatizaciones",
"auto_h2": "Lo que hoy hacés a mano en tu Tiendanube, que se haga solo.",
"auto_lead": "Conectamos tu tienda con las herramientas que ya usás. Se ve en un trabajo real: cuando el pago se acredita, el sistema da de alta al alumno y le abre el acceso, a cualquier hora y sin que nadie del equipo haga nada.",
"autos": [
  ("tiendanube.png", "Venta aprobada, alta automática", "Al acreditarse el pago, la tienda avisa y Make hace el resto: alta del cliente, accesos o aviso interno.", True),
  ("make.svg", "Sin tareas repetitivas", "Pedidos a una planilla o a tu CRM, avisos al equipo y mensajes de seguimiento. Lo armamos según tu caso.", False),
  ("whatsapp.svg", "Consultas bien repartidas", "Las consultas de WhatsApp se reparten entre asesores y cada una queda registrada con su origen.", False),
  ("googlesheets.svg", "Todo en un solo lugar", "Cada venta y cada consulta quedan ordenadas para saber qué funciona y dónde se pierden clientes.", False),
],
"auto_link": ("servicio-automatizacion-leads.html", "Ver el servicio de automatización"),
"proceso_lead": "Antes de empezar tenés el alcance, el plazo y el precio por escrito. Hablás siempre con quien está armando tu tienda.",
"pasos": [
  ("Diagnóstico", "Hablamos de qué vendés, cuántos productos tenés, cómo cobrás y cómo entregás. Con eso confirmamos si Tiendanube es la plataforma indicada o si te conviene otra.", "Sin cargo"),
  ("Propuesta", "Te pasamos qué incluye la tienda, cuánto tarda, cuánto sale y lo que cuesta mantener el plan de Tiendanube por mes.", ""),
  ("Diseño", "Ves la tienda diseñada con tus productos reales antes de armarla. La ajustamos con vos hasta que te cierre.", ""),
  ("Armado y carga", "Cargamos el catálogo, configuramos pagos y envíos, y hacemos compras de prueba reales hasta que todo sale bien.", ""),
  ("Lanzamiento y capacitación", "La publicamos en tu dominio y te enseñamos a cargar productos, ver pedidos y armar promociones. Después del lanzamiento hay una ronda de ajustes incluida.", "Seguimos disponibles para soporte"),
],
"casos": [
  ("caso-tienda-a-medida.html", "tienda-a-medida.jpg", "Tienda con menú programado a medida", "E-commerce a medida", "Una tienda con el menú programado a medida"),
  ("caso-plataforma-de-cursos.html", "plataforma-de-cursos.jpg", "Tiendanube, Make y aula virtual conectados", "Desarrollo a medida", "El alumno paga y entra al aula solo"),
  ("caso-retail-rubro-restringido.html", "retail-rubro-restringido.jpg", "Campañas de Google Ads para una tienda", "Gestión de campañas", "Google Ads en un rubro con restricciones"),
],
"casos_lead": "Cada caso cuenta el problema que había, cómo lo encaramos y qué cambió.",
"faq": [
  ("¿Cuánto cuesta una tienda en Tiendanube?", "Depende del diseño, de la cantidad de productos y de las funciones que necesites, por eso no hay un precio único. Después de la reunión te pasamos un precio cerrado por escrito. Aparte está el abono de Tiendanube, que pagás directo a la plataforma según el plan que elijas."),
  ("¿Cuánto tarda en estar lista?", "Una tienda completa lleva entre 3 y 6 semanas. Lo que más mueve el plazo es tener las fotos y los datos de los productos listos. Antes de arrancar tenés el cronograma con las fechas de cada etapa."),
  ("¿Se puede personalizar el diseño más allá de las plantillas?", "Sí. Escribimos el diseño sobre el tema de tu tienda. En un caso, una tienda con más de ochocientos productos y sesenta y nueve categorías necesitaba un menú con foto por categoría, que la plataforma no trae, y lo programamos. Trabajamos primero en una copia, para no tocar la tienda que vende."),
  ("Tengo una tienda en WooCommerce, Shopify u otra plataforma. ¿Pueden pasarla a Tiendanube?", "Sí. Pasamos productos, fotos y categorías, y redirigimos las direcciones viejas a las nuevas. La tienda vieja sigue andando hasta que la nueva está lista."),
  ("¿Qué pasa con mi posicionamiento en Google si migro?", "Redirigimos cada dirección vieja a la nueva con redirecciones 301, conservamos los títulos y textos que ya rinden y revisamos la indexación después de lanzar. Así Google no pierde lo que ya conocía de tu tienda."),
  ("¿Se conecta con Mercado Pago?", "Sí. Configuramos Mercado Pago junto con los otros medios de pago que trae Tiendanube (tarjeta, transferencia y cuotas), con sus recargos y promociones, y probamos una compra real antes de lanzar."),
  ("¿Pueden automatizar tareas de mi tienda?", "Sí, según tu caso. Por ejemplo, conectamos una tienda de cursos con su aula virtual: cuando el pago se acredita, el sistema da de alta al alumno y le abre el acceso solo, a cualquier hora. También armamos avisos de venta y el reparto de consultas de WhatsApp."),
  ("¿Me conviene Tiendanube, Shopify o WooCommerce?", "Depende de cuántos productos tenés, en qué países vendés y quién va a manejar la tienda. Tiendanube es simple y trae pagos y envíos de la región ya integrados. Shopify conviene si vendés en varios países o monedas, y WooCommerce si querés la tienda dentro de WordPress y sin abono de plataforma. En la reunión te recomendamos una y te explicamos por qué."),
  ("¿La tienda queda a mi nombre?", "Siempre. La cuenta de Tiendanube, el dominio y los medios de cobro son tuyos. Nosotros los configuramos y te dejamos todos los accesos."),
],
"rel": [
  ("servicio-tiendas-online.html", "tji-budget", "Tiendas online", "Tiendanube, Shopify o WooCommerce: cómo elegir la plataforma."),
  ("servicio-shopify.html", "tji-budget", "Tiendas en Shopify", "Para vender en varios países y monedas."),
  ("servicio-woocommerce.html", "tji-budget", "Tiendas en WooCommerce", "La tienda dentro de WordPress, sin abono de plataforma."),
  ("servicio-automatizacion-leads.html", "tji-bell", "Automatización de leads", "Que ninguna consulta se enfríe y cada una quede registrada."),
],
"cierre_h2": '¿Arrancamos con tu <span class="sc-sv-grad">tienda en Tiendanube</span>?',
"cierre_p": "Media hora de reunión y te decimos si Tiendanube es la plataforma indicada, cuánto tarda y cuánto sale.",
"wa_texto": "Hola, quiero consultar por una tienda en Tiendanube",
},

{
"archivo": "servicio-shopify.html",
"nombre": "Shopify",
"logo": ("shopify.svg", "Logo de Shopify", False),
"title": "Desarrollo de Tiendas Shopify a Medida - Studio Complex",
"desc": "Armamos tu tienda en Shopify a medida: varios países y monedas, aplicaciones justas, Mercado Pago, carga de productos y SEO. Precio cerrado por escrito.",
"service_name": "Tiendas en Shopify",
"service_type": "Desarrollo y migración de tiendas online en Shopify",
"eyebrow": "Shopify",
"h1": 'Tu tienda en <span class="sc-sv-grad">Shopify</span>, lista para crecer.',
"lead": "Armamos tu tienda en Shopify con diseño propio, catálogo cargado, pagos y envíos resueltos y SEO desde el primer día. Es la plataforma que conviene cuando vendés en varios países o en varias monedas, o cuando necesitás funciones avanzadas. También te mudamos desde otra plataforma sin perder el posicionamiento.",
"datos": [("3 a 6 sem.", "para una tienda completa"), ("Varios", "países y monedas"), ("Miles", "de aplicaciones")],
"cinta": ["Diseño a medida", "Varios países y monedas", "Mercado Pago", "Aplicaciones justas", "Carga de productos", "SEO de la tienda", "Migración sin perder Google", "Píxel y analítica", "Automatizaciones"],
"formatos_eyebrow": "Cómo trabajamos",
"formatos_h2": "Tres formas de empezar con Shopify.",
"formatos_lead": "Shopify es muy completa y tiene miles de aplicaciones. Brilla cuando vendés en varios países o necesitás funciones avanzadas. Según dónde estés parado, arrancamos de una de estas tres maneras.",
"formatos": [
  ("De 3 a 6 semanas", "Tienda nueva en Shopify", "Tu tienda desde cero, con diseño propio, los productos cargados y los pagos, los envíos y los países en los que vendés configurados.",
   ["Diseño a medida de tu marca", "Carga del catálogo", "Países, monedas, pagos y envíos"], "querés vender en más de un país o prepararte para crecer.", False),
  ("Según el alcance", "Funciones avanzadas", "Para tiendas que ya venden y necesitan más: elegimos las aplicaciones justas y programamos lo que ninguna aplicación resuelve.",
   ["Aplicaciones elegidas y configuradas", "Funciones propias del rubro", "Capacitación al entregar"], "tu tienda ya vende y ahora tiene que vender más.", True),
  ("Según la cantidad de productos", "Migración a Shopify", "Te mudamos desde WooCommerce, Tiendanube u otra plataforma, con productos, fotos y categorías, y cuidamos lo que Google ya conocía.",
   ["Productos, variantes y colecciones", "Redirecciones 301, una por una", "Tienda nueva lista antes de apagar la vieja"], "tu plataforma actual te limita o te cobra de más.", False),
],
"incluye_eyebrow": "Qué incluye",
"incluye_h2": "Tu tienda en Shopify, lista para vender y para que te encuentren.",
"cajas": [
  ("tji-development", "Diseño propio sobre tu tema", "Personalizamos el tema de tu tienda para que se vea como tu marca y se compre cómodo desde el teléfono. Trabajamos primero en una copia, para no tocar la tienda que vende."),
  ("tji-budget", "Cobrás como tu cliente quiere pagar", "Mercado Pago, tarjetas en cuotas y transferencia, con recargos y promociones por país. Cerramos con una compra real de prueba antes de lanzar."),
  ("tji-plane", "Varios países y monedas", "Configuramos los países en los que vendés, las monedas y los envíos de cada uno, para que el cliente vea el precio y el costo final antes de pagar."),
  ("tji-window", "Aplicaciones justas, con la cuenta hecha", "Shopify tiene un costo mensual más alto y varias funciones se pagan aparte. Elegimos solo las aplicaciones que necesitás y te mostramos cuánto suman por mes antes de decidir."),
  ("tji-search", "SEO de tu tienda", "Optimizamos títulos, descripciones y direcciones de productos y colecciones, sumamos datos estructurados y cuidamos la velocidad, para que Google entienda lo que vendés."),
  ("tji-chart", "Lista para anunciar", "El píxel de Meta, Google Analytics y el seguimiento de compras quedan instalados y probados. Así, cuando arranques con Google Ads o Meta Ads, cada venta se atribuye a su campaña."),
  ("tji-bell", "Carritos que vuelven", "Quien deja productos en el carrito recibe un recordatorio y vuelve a cerrar la compra. Sumamos también el botón de WhatsApp para quien prefiere consultar antes."),
],
"auto_eyebrow": "Automatizaciones",
"auto_h2": "Lo que hoy hacés a mano en tu Shopify, que se haga solo.",
"auto_lead": "Conectamos tu tienda con las herramientas que ya usás. Se ve en un trabajo real que hicimos con Tiendanube: cuando el pago se acredita, el sistema da de alta al alumno y le abre el acceso, a cualquier hora y sin que nadie del equipo haga nada.",
"autos": [
  ("shopify.svg", "Venta aprobada, aviso automático", "Cuando se acredita un pago, Make registra la venta y avisa a quien corresponda: tu equipo, tu CRM o el cliente.", False),
  ("make.svg", "Sin tareas repetitivas", "Pedidos que pasan solos a una planilla o a tu sistema, y mensajes de seguimiento sin escribirlos uno por uno.", False),
  ("whatsapp.svg", "Consultas bien repartidas", "Cada consulta de WhatsApp llega al asesor que corresponde y queda registrada con su origen.", False),
  ("googlesheets.svg", "Todo en un solo lugar", "Ventas y consultas ordenadas para ver qué funciona y en qué paso se pierden clientes.", False),
],
"auto_link": ("servicio-automatizacion-leads.html", "Ver el servicio de automatización"),
"proceso_lead": "Antes de empezar tenés por escrito el alcance, el plazo y el costo total, con las aplicaciones incluidas. Hablás siempre con quien arma tu tienda.",
"pasos": [
  ("Diagnóstico", "Hablamos de qué vendés, en qué países, cuántos productos tenés, cómo cobrás y cómo entregás. Con eso confirmamos si Shopify es la plataforma indicada o si te conviene otra.", "Sin cargo"),
  ("Propuesta", "Te pasamos qué incluye la tienda, cuánto tarda, cuánto sale y lo que cuesta mantener el plan de Shopify y las aplicaciones por mes.", ""),
  ("Diseño", "Antes de armar nada ves el diseño con tus productos reales y los países en los que vas a vender. Lo ajustamos juntos hasta que te cierre.", ""),
  ("Armado y carga", "Cargamos el catálogo, configuramos países, monedas, pagos y envíos, y repetimos compras de prueba reales hasta que todo sale bien.", ""),
  ("Lanzamiento y capacitación", "Publicamos la tienda en tu dominio y te capacitamos para cargar productos, seguir pedidos y armar promociones. Tras el lanzamiento hay una ronda de ajustes incluida.", "Seguimos disponibles para soporte"),
],
"casos_h2": "Cómo trabajamos una tienda.",
"casos_lead": "Todavía no publicamos un caso en Shopify. Estos trabajos son de tiendas en otras plataformas y siguen el mismo proceso que aplicamos acá.",
"casos": [
  ("caso-tienda-a-medida.html", "tienda-a-medida.jpg", "Tienda con menú programado a medida", "E-commerce a medida", "Una tienda con el menú programado a medida"),
  ("caso-plataforma-de-cursos.html", "plataforma-de-cursos.jpg", "Tienda, Make y aula virtual conectados", "Desarrollo a medida", "El alumno paga y entra al aula solo"),
  ("caso-retail-rubro-restringido.html", "retail-rubro-restringido.jpg", "Campañas de Google Ads para una tienda", "Gestión de campañas", "Google Ads en un rubro con restricciones"),
],
"faq": [
  ("¿Cuánto cuesta una tienda en Shopify?", "Depende del diseño, de la cantidad de productos y de las funciones que necesites, por eso no hay un precio único. Después de la reunión te pasamos un precio cerrado por escrito. Aparte está el abono de Shopify y las aplicaciones que uses, que pagás directo a cada servicio."),
  ("¿Cuánto tarda en estar lista?", "Una tienda completa lleva entre 3 y 6 semanas. Lo que más mueve el plazo es tener listos las fotos y los datos de los productos, y definir desde el principio países, monedas y aplicaciones. Antes de arrancar tenés el cronograma por etapas."),
  ("¿Cuándo conviene Shopify?", "Cuando vendés en varios países o en varias monedas, o cuando necesitás funciones avanzadas que resuelve una aplicación de su tienda. Si vendés en un solo país y querés salir rápido, muchas veces conviene más Tiendanube. En la reunión te recomendamos una y te explicamos por qué."),
  ("¿Cuánto cuestan las aplicaciones de Shopify?", "Shopify tiene un costo mensual más alto y varias funciones se pagan aparte. Por eso, antes de armar la tienda te mostramos qué aplicaciones necesitás y cuánto suman por mes, para que hagas la cuenta completa."),
  ("Tengo una tienda en WooCommerce, Tiendanube u otra plataforma. ¿Pueden pasarla a Shopify?", "Sí. Pasamos productos, fotos y categorías, y redirigimos las direcciones viejas a las nuevas. La tienda vieja sigue andando hasta que la nueva está lista."),
  ("¿Qué pasa con mi posicionamiento en Google si migro?", "Cada dirección vieja se redirige a la nueva con una redirección 301, una por una, porque Shopify arma sus propias direcciones. Conservamos los títulos y textos que ya rinden y revisamos la indexación después de lanzar."),
  ("¿Se conecta con Mercado Pago?", "Sí. Lo conectamos y lo configuramos junto con tarjeta, transferencia y cuotas, con sus recargos y promociones, y hacemos una compra real antes de lanzar."),
  ("¿Pueden automatizar tareas de mi tienda?", "Sí, según tu caso. Un ejemplo real, con otra plataforma: al acreditarse el pago, el sistema da de alta al alumno y le abre el acceso a cualquier hora. Con Shopify podemos armar avisos de venta, registros en planilla o CRM y el reparto de consultas de WhatsApp."),
  ("¿La tienda queda a mi nombre?", "Siempre. La cuenta de Shopify, el dominio y los medios de cobro quedan a tu nombre, y te dejamos todos los accesos."),
],
"rel": [
  ("servicio-tiendas-online.html", "tji-budget", "Tiendas online", "Tiendanube, Shopify o WooCommerce: cómo elegir la plataforma."),
  ("servicio-tiendanube.html", "tji-budget", "Tiendas en Tiendanube", "Simple de manejar y con pagos y envíos de la región integrados."),
  ("servicio-woocommerce.html", "tji-budget", "Tiendas en WooCommerce", "La tienda dentro de WordPress, sin abono de plataforma."),
  ("servicio-seo-tecnico.html", "tji-search", "SEO Técnico", "Que te encuentren en Google cuando te buscan."),
],
"cierre_h2": '¿Arrancamos con tu <span class="sc-sv-grad">tienda en Shopify</span>?',
"cierre_p": "Media hora de reunión y te decimos si Shopify es la plataforma indicada, cuánto tarda y cuánto sale.",
"wa_texto": "Hola, quiero consultar por una tienda en Shopify",
},
{
"archivo": "servicio-woocommerce.html",
"nombre": "WooCommerce",
"logo": ("woocommerce.svg", "Logo de WooCommerce", False),
"title": "Tiendas WooCommerce en WordPress a Medida - Studio Complex",
"desc": "Armamos tu tienda en WooCommerce sobre WordPress: sin abono de plataforma, precios mayoristas, catálogos con reglas propias y SEO. Precio cerrado por escrito.",
"service_name": "Tiendas en WooCommerce",
"service_type": "Desarrollo y migración de tiendas online en WooCommerce sobre WordPress",
"eyebrow": "WooCommerce",
"h1": 'Tu tienda en <span class="sc-sv-grad">WooCommerce</span>, dentro de tu WordPress.',
"lead": "Armamos tu tienda en WooCommerce sobre WordPress: sin abono de plataforma, flexible para catálogos con reglas propias, como precios mayoristas o productos a medida, e integrada con el contenido de tu sitio. También te mudamos desde otra plataforma sin perder el posicionamiento.",
"datos": [("3 a 6 sem.", "para una tienda completa"), ("Sin abono", "de plataforma"), ("WordPress", "tienda y contenido juntos")],
"cinta": ["Diseño a medida", "Sin abono de plataforma", "Precios mayoristas", "Productos a medida", "Mercado Pago", "Carga de productos", "SEO de la tienda", "Migración sin perder Google", "Píxel y analítica"],
"formatos_eyebrow": "Cómo trabajamos",
"formatos_h2": "Tres formas de empezar con WooCommerce.",
"formatos_lead": "WooCommerce vive dentro de WordPress, no tiene abono de plataforma y se adapta a catálogos con reglas propias. A cambio, necesita más mantenimiento técnico, y por eso te lo explicamos antes de arrancar.",
"formatos": [
  ("De 3 a 6 semanas", "Tienda nueva en WooCommerce", "Tu tienda sobre WordPress desde cero, con diseño propio, los productos cargados y los pagos y envíos funcionando.",
   ["Diseño propio sobre WordPress", "Carga del catálogo", "Pagos, envíos y analítica"], "querés una tienda integrada con el contenido de tu sitio y sin abono de plataforma.", False),
  ("Según el alcance", "Catálogo con reglas propias", "Para precios mayoristas, productos configurables o a medida, y cualquier regla que las otras plataformas no resuelven.",
   ["Precios mayoristas y por cliente", "Productos configurables", "Capacitación al entregar"], "tu catálogo tiene reglas especiales que la plantilla no cubre.", True),
  ("Según la cantidad de productos", "Migración a WooCommerce", "Te mudamos desde Tiendanube, Shopify u otra plataforma, con productos, fotos y categorías, y cuidamos lo que Google ya conocía.",
   ["Productos, variantes y categorías", "Redirecciones y enlaces permanentes", "La vieja sigue hasta que la nueva está lista"], "tu plataforma actual te limita o te cobra de más.", False),
],
"incluye_eyebrow": "Qué incluye",
"incluye_h2": "Tu tienda en WooCommerce, lista para vender y para que te encuentren.",
"cajas": [
  ("tji-development", "Diseño propio sobre WordPress", "Armamos el diseño a medida de tu marca, pensado para comprar cómodo desde el teléfono. Trabajamos primero en una copia, para no tocar la tienda que vende."),
  ("tji-budget", "Cobrás como tu cliente quiere pagar", "Mercado Pago, tarjetas en cuotas y transferencia dentro del checkout de WooCommerce, con sus recargos y promociones. Validamos todo con una compra real antes de lanzar."),
  ("tji-window", "Catálogo cargado", "Importamos tu catálogo con fotos, variantes, stock y precios, y ordenamos las categorías para que se navegue fácil. Si ya tenés una planilla, partimos de ahí."),
  ("tji-plane", "Reglas propias de tu rubro", "Precios mayoristas, productos a medida o configurables: lo programamos para que tu tienda venda como vendés vos, sin forzar al cliente a escribirte."),
  ("tji-search", "SEO de tu tienda y de tu contenido", "Títulos y descripciones por producto y categoría, direcciones claras, datos estructurados y velocidad. Y como todo vive en WordPress, tu blog y tu tienda se potencian entre sí."),
  ("tji-chart", "Lista para anunciar", "Instalamos y probamos el píxel de Meta, Google Analytics y el seguimiento de compras, para que los anuncios que prendas después midan ventas reales de tu tienda."),
  ("tji-bell", "Mantenimiento sin sorpresas", "Sin abono de plataforma, pagás el alojamiento y los complementos que uses, y la tienda necesita actualizaciones. Te mostramos qué implica y seguimos disponibles para soporte."),
],
"auto_eyebrow": "Automatizaciones",
"auto_h2": "Lo que hoy hacés a mano en tu WooCommerce, que se haga solo.",
"auto_lead": "Conectamos tu tienda con las herramientas que ya usás. Se ve en un trabajo real que hicimos con otra plataforma: cuando el pago se acredita, el sistema da de alta al alumno y le abre el acceso, a cualquier hora y sin que nadie del equipo haga nada.",
"autos": [
  ("woocommerce.svg", "Pedido pagado, aviso automático", "Cuando WooCommerce confirma un pago, Make registra el pedido y avisa a tu equipo, a tu CRM o al cliente.", False),
  ("make.svg", "Sin tareas repetitivas", "Los pedidos viajan solos a una planilla o a tu sistema de gestión, y el seguimiento al cliente se manda sin copiar y pegar.", False),
  ("whatsapp.svg", "Consultas bien repartidas", "Las consultas de WhatsApp se reparten entre asesores y cada una queda anotada con su origen.", False),
  ("googlesheets.svg", "Todo en un solo lugar", "Cada venta y cada consulta quedan ordenadas para saber qué anda bien y dónde se enfrían los clientes.", False),
],
"auto_link": ("servicio-automatizacion-leads.html", "Ver el servicio de automatización"),
"proceso_lead": "Antes de empezar tenés por escrito el alcance, el plazo y lo que cuesta mantener la tienda. Hablás siempre con quien la está armando.",
"pasos": [
  ("Diagnóstico", "Hablamos de qué vendés, qué reglas tiene tu catálogo, cómo cobrás y cómo entregás. Con eso confirmamos si WooCommerce es la plataforma indicada o si te conviene otra.", "Sin cargo"),
  ("Propuesta", "Te pasamos qué incluye la tienda, cuánto tarda, cuánto sale y lo que cuesta mantenerla por mes: alojamiento, complementos y actualizaciones.", ""),
  ("Diseño", "Te mostramos el diseño con tus productos reales y las reglas de precio que pediste, antes de armar. Lo ajustamos hasta que te cierre.", ""),
  ("Armado y carga", "Cargamos el catálogo, programamos las reglas de precio, configuramos pagos y envíos y hacemos compras de prueba reales hasta que todo sale bien.", ""),
  ("Lanzamiento y capacitación", "Publicamos en tu dominio y te enseñamos a manejar productos, pedidos y promociones, y qué actualizaciones hacer. Hay una ronda de ajustes incluida después del lanzamiento.", "Seguimos disponibles para soporte"),
],
"casos_h2": "Cómo trabajamos una tienda.",
"casos_lead": "Todavía no publicamos un caso en WooCommerce. Estos trabajos son de tiendas en otras plataformas y siguen el mismo proceso que aplicamos acá.",
"casos": [
  ("caso-tienda-a-medida.html", "tienda-a-medida.jpg", "Tienda con menú programado a medida", "E-commerce a medida", "Una tienda con el menú programado a medida"),
  ("caso-marker-webflow.html", "marker-webflow.jpg", "Migración de WordPress a Webflow", "Migración", "De WordPress a un ecosistema digital en Webflow"),
  ("caso-retail-rubro-restringido.html", "retail-rubro-restringido.jpg", "Campañas de Google Ads para una tienda", "Gestión de campañas", "Google Ads en un rubro con restricciones"),
],
"faq": [
  ("¿Cuánto cuesta una tienda en WooCommerce?", "Depende del diseño, de la cantidad de productos y de las reglas que necesite tu catálogo, por eso no hay un precio único. Después de la reunión te pasamos un precio cerrado por escrito. WooCommerce no tiene abono de plataforma: aparte pagás el alojamiento y los complementos que uses."),
  ("¿Cuánto tarda en estar lista?", "Una tienda completa lleva entre 3 y 6 semanas. El plazo depende sobre todo de las fotos y los datos de los productos y de cuántas reglas de precio haya que programar. Antes de arrancar tenés el cronograma con las fechas de cada etapa."),
  ("¿Cuándo conviene WooCommerce?", "Cuando tu catálogo tiene reglas propias, como precios mayoristas, cotización o productos configurables, o cuando querés la tienda dentro de un sitio WordPress con su contenido. Si vendés en un solo país y querés salir rápido con poco mantenimiento, muchas veces conviene más Tiendanube. En la reunión te recomendamos una y te explicamos por qué."),
  ("¿Se pueden hacer precios mayoristas o productos a medida?", "Sí. WooCommerce es muy flexible para catálogos con reglas propias, como precios mayoristas o productos a medida, y lo programamos según tu rubro."),
  ("¿Qué mantenimiento necesita?", "Más que una plataforma cerrada: actualizaciones y complementos al día, y el alojamiento. Antes de arrancar te explicamos qué implica y cuánto cuesta por mes, y después seguimos disponibles para soporte."),
  ("Tengo una tienda en Tiendanube, Shopify u otra plataforma. ¿Pueden pasarla a WooCommerce?", "Sí. Pasamos productos, fotos y categorías y redirigimos las direcciones viejas a las nuevas, para no perder lo que Google ya conocía. Hasta que la nueva no está lista, la vieja sigue funcionando."),
  ("¿Se conecta con Mercado Pago?", "Sí. Configuramos Mercado Pago dentro del checkout de WooCommerce, junto con tarjeta, transferencia y cuotas, y hacemos una compra real antes de lanzar."),
  ("¿Pueden automatizar tareas de mi tienda?", "Sí, según tu caso. Un ejemplo real, con otra plataforma: al acreditarse el pago, el sistema da de alta al alumno y le abre el acceso a cualquier hora. Con WooCommerce podemos armar avisos de pedido, registros en planilla o CRM y el reparto de consultas de WhatsApp."),
  ("¿La tienda queda a mi nombre?", "Siempre. El sitio, el dominio y los medios de cobro son tuyos. Nosotros los configuramos y te dejamos todos los accesos."),
],
"rel": [
  ("servicio-tiendas-online.html", "tji-budget", "Tiendas online", "Tiendanube, Shopify o WooCommerce: cómo elegir la plataforma."),
  ("servicio-tiendanube.html", "tji-budget", "Tiendas en Tiendanube", "Simple de manejar y con pagos y envíos de la región integrados."),
  ("servicio-shopify.html", "tji-budget", "Tiendas en Shopify", "Para vender en varios países y monedas."),
  ("servicio-desarrollo-web.html", "tji-development", "Desarrollo web", "Sitios a medida, rápidos y editables por vos."),
],
"cierre_h2": '¿Arrancamos con tu <span class="sc-sv-grad">tienda en WooCommerce</span>?',
"cierre_p": "Media hora de reunión y te decimos si WooCommerce es la plataforma indicada, cuánto tarda y cuánto sale.",
"wa_texto": "Hola, quiero consultar por una tienda en WooCommerce",
},
]
